// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webscan.Scheduler.datastore;

namespace Webscan.Scheduler.Migrations
{
    [DbContext(typeof(WebscanContext))]
    [Migration("20201123220516_InitialMigration3")]
    partial class InitialMigration3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Webscan.Scheduler.Models.StatusCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("XPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XPathContentFailureString")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("StatusChecks");
                });

            modelBuilder.Entity("Webscan.Scheduler.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Webscan.Scheduler.Models.StatusCheck", b =>
                {
                    b.HasOne("Webscan.Scheduler.Models.User", null)
                        .WithMany("StatusChecks")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Webscan.Scheduler.Models.User", b =>
                {
                    b.Navigation("StatusChecks");
                });
#pragma warning restore 612, 618
        }
    }
}
