// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webscan.Scheduler.datastore;

namespace Webscan.Scheduler.Migrations
{
    [DbContext(typeof(WebscanContext))]
    [Migration("20201210185233_dbInit")]
    partial class dbInit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Webscan.Scheduler.Models.StatusCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CronExpression")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastNotified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QueryTimeInSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XPathContentFailureString")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StatusChecks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CronExpression = "* * * * *",
                            Enabled = false,
                            LastNotified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "NewEgg: EVGA 3080 FTW3",
                            QueryTimeInSeconds = 0,
                            Url = "https://www.newegg.com/evga-geforce-rtx-3080-10g-p5-3897-kr/p/N82E16814487518?Description=3080%20ftw&cm_re=3080_ftw-_-14-487-518-_-Product",
                            XPath = "//*[@id=\"ProductBuy\"]/div/div/span",
                            XPathContentFailureString = "Sold Out"
                        },
                        new
                        {
                            Id = 2,
                            CronExpression = "* * * * *",
                            Enabled = false,
                            LastNotified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "BestBuy: AMD 5900x",
                            QueryTimeInSeconds = 0,
                            Url = "https://www.bestbuy.com/site/amd-ryzen-9-5900x-4th-gen-12-core-24-threads-unlocked-desktop-processor-without-cooler/6438942.p?skuId=6438942",
                            XPath = "/html/body/div[3]/main/div[2]/div[3]/div[2]/div/div/div[6]/div[1]/div/div/div/button",
                            XPathContentFailureString = "Sold Out"
                        },
                        new
                        {
                            Id = 3,
                            CronExpression = "* * * * *",
                            Enabled = false,
                            LastNotified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "BestBuy: AMD 5600x",
                            QueryTimeInSeconds = 0,
                            Url = "https://www.bestbuy.com/site/amd-ryzen-5-5600x-4th-gen-6-core-12-threads-unlocked-desktop-processor-with-wraith-stealth-cooler/6438943.p?skuId=6438943",
                            XPath = "/html/body/div[3]/main/div[2]/div[3]/div[2]/div/div/div[6]/div[1]/div/div/div/button",
                            XPathContentFailureString = "Sold Out"
                        },
                        new
                        {
                            Id = 4,
                            Enabled = false,
                            LastNotified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "NewEgg: EVGA 3080 XC3",
                            QueryTimeInSeconds = 30,
                            Url = "https://www.newegg.com/evga-geforce-rtx-3080-10g-p5-3885-kr/p/N82E16814487520?Description=3080&cm_re=3080-_-14-487-520-_-Product&quicklink=true",
                            XPath = "//*[@id=\"ProductBuy\"]/div/div/span",
                            XPathContentFailureString = "Sold Out"
                        },
                        new
                        {
                            Id = 5,
                            Enabled = false,
                            LastNotified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "NewEgg: Asus 3080 TUF",
                            QueryTimeInSeconds = 30,
                            Url = "https://www.newegg.com/asus-geforce-rtx-3080-tuf-rtx3080-o10g-gaming/p/N82E16814126452?Description=3080&cm_re=3080-_-14-126-452-_-Product",
                            XPath = "//*[@id=\"ProductBuy\"]/div/div/span",
                            XPathContentFailureString = "Sold Out"
                        },
                        new
                        {
                            Id = 6,
                            Enabled = false,
                            LastNotified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "NewEgg: Gigabyte 3080 Auros",
                            QueryTimeInSeconds = 30,
                            Url = "https://www.newegg.com/gigabyte-geforce-rtx-3080-gv-n3080vision-oc-10gd/p/N82E16814932337?Description=3080&cm_re=3080-_-14-932-337-_-Product",
                            XPath = "//*[@id=\"ProductBuy\"]/div/div/span",
                            XPathContentFailureString = "Sold Out"
                        },
                        new
                        {
                            Id = 7,
                            Enabled = false,
                            LastNotified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "NewEgg: PNY 3080",
                            QueryTimeInSeconds = 30,
                            Url = "https://www.newegg.com/pny-geforce-rtx-3080-vcg308010tfxmpb/p/N82E16814133810?Description=3080&cm_re=3080-_-14-133-810-_-Product",
                            XPath = "//*[@id=\"ProductBuy\"]/div/div/span",
                            XPathContentFailureString = "Out of Stock "
                        },
                        new
                        {
                            Id = 8,
                            Enabled = false,
                            LastNotified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "NewEgg: ASUS ROG 3080 Strix",
                            QueryTimeInSeconds = 30,
                            Url = "https://www.newegg.com/asus-geforce-rtx-3080-rog-strix-rtx3080-o10g-gaming/p/N82E16814126457?Description=3080&cm_re=3080-_-14-126-457-_-Product",
                            XPath = "//*[@id=\"ProductBuy\"]/div/div/span",
                            XPathContentFailureString = "Sold Out"
                        },
                        new
                        {
                            Id = 9,
                            Enabled = false,
                            LastNotified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "NewEgg: AMD 5900x CPU",
                            QueryTimeInSeconds = 30,
                            Url = "https://www.newegg.com/amd-ryzen-9-5900x/p/N82E16819113664?Description=5900x&cm_re=5900x-_-19-113-664-_-Product",
                            XPath = "//*[@id=\"ProductBuy\"]/div/div/span",
                            XPathContentFailureString = "Sold Out"
                        },
                        new
                        {
                            Id = 10,
                            Enabled = false,
                            LastNotified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "NewEgg: AMD 5600x CPU",
                            QueryTimeInSeconds = 30,
                            Url = "https://www.newegg.com/amd-ryzen-5-5600x/p/N82E16819113666?Description=5600x&cm_re=5600x-_-19-113-666-_-Product",
                            XPath = "//*[@id=\"ProductBuy\"]/div/div/span",
                            XPathContentFailureString = "Sold Out"
                        },
                        new
                        {
                            Id = 11,
                            CronExpression = "* * * * *",
                            Enabled = false,
                            LastNotified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "B&H: AMD 5900x CPU",
                            QueryTimeInSeconds = 0,
                            Url = "https://www.bhphotovideo.com/c/product/1598373-REG/amd_100_100000061wof_ryzen_9_5900x_3_7.html",
                            XPath = "//*[@id=\"bh-app\"]/section/div/div[2]/div[4]/div/div[2]/div/div/div[6]/div[1]/div[1]/div/button",
                            XPathContentFailureString = "Notify When Available"
                        },
                        new
                        {
                            Id = 12,
                            CronExpression = "* * * * *",
                            Enabled = false,
                            LastNotified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "B&H: AMD 5600x CPU",
                            QueryTimeInSeconds = 0,
                            Url = "https://www.bhphotovideo.com/c/product/1598377-REG/amd_100_100000065box_ryzen_5_5600x_3_7.html",
                            XPath = "//*[@id=\"bh-app\"]/section/div/div[2]/div[4]/div/div[2]/div/div/div[6]/div[1]/div[1]/div/button",
                            XPathContentFailureString = "Notify When Available"
                        },
                        new
                        {
                            Id = 13,
                            CronExpression = "* * * * *",
                            Enabled = false,
                            LastNotified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "B&H: AMD 5800x CPU",
                            QueryTimeInSeconds = 0,
                            Url = "https://www.bhphotovideo.com/c/product/1598376-REG/amd_100_100000063wof_ryzen_7_5800x_3_8.html",
                            XPath = "//*[@id=\"bh-app\"]/section/div/div[2]/div[4]/div/div[2]/div/div/div[6]/div[1]/div[1]/div/button",
                            XPathContentFailureString = "Notify When Available"
                        },
                        new
                        {
                            Id = 14,
                            CronExpression = "* * * * *",
                            Enabled = false,
                            LastNotified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "B&H: ASUS 3070 GPU",
                            QueryTimeInSeconds = 0,
                            Url = "https://www.bhphotovideo.com/c/product/1602755-REG/asus_dualrtx30708g_geforce_rtx_3070_8g.html",
                            XPath = "//*[@id=\"bh-app\"]/section/div/div[2]/div[4]/div/div[2]/div/div/div[6]/div[1]/div[1]/div/button",
                            XPathContentFailureString = "Notify When Available"
                        },
                        new
                        {
                            Id = 15,
                            CronExpression = "* * * * *",
                            Enabled = false,
                            LastNotified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Microcenter Instore ONLY St. Louis Park: EVGA 3080 FTW",
                            QueryTimeInSeconds = 0,
                            Url = "https://www.microcenter.com/product/628346/evga-geforce-rtx-3080-ftw3-ultra-gaming-triple-fan-10gb-gddr6x-pcie-40-graphics-card?storeid=045",
                            XPath = "//*[@id=\"pnlInventory\"]/p/span",
                            XPathContentFailureString = "Sold Out"
                        },
                        new
                        {
                            Id = 16,
                            CronExpression = "* * * * *",
                            Enabled = false,
                            LastNotified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Microcenter Instore ONLY St. Louis Park: ASUS TUF 3080",
                            QueryTimeInSeconds = 0,
                            Url = "https://www.microcenter.com/product/628318/asus-geforce-rtx-3080-tuf-gaming-overclocked-triple-fan-10gb-gddr6x-pcie-40-graphics-card?storeid=045",
                            XPath = "//*[@id=\"pnlInventory\"]/p/span",
                            XPathContentFailureString = "Sold Out"
                        },
                        new
                        {
                            Id = 17,
                            CronExpression = "* * * * *",
                            Enabled = false,
                            LastNotified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Microcenter Instore ONLY St. Louis Park: EVGA 3070 XC3",
                            QueryTimeInSeconds = 0,
                            Url = "https://www.microcenter.com/product/630578/evga-geforce-rtx-3070-xc3-ultra-gaming-triple-fan-8gb-gddr6-pcie-40-graphics-card?storeid=045",
                            XPath = "//*[@id=\"pnlInventory\"]/p/span",
                            XPathContentFailureString = "Sold Out"
                        },
                        new
                        {
                            Id = 18,
                            CronExpression = "* * * * *",
                            Enabled = true,
                            LastNotified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "AMD.com: 5000 Series Processors",
                            QueryTimeInSeconds = 0,
                            Url = "https://www.amd.com/en/where-to-buy/ryzen-5000-series-processors",
                            XPath = "/html/body/div[1]/main/div/div/div/article/div/div[1]/div[1]/div[2]/div/div[1]/div/div/div/div[2]/div/p/a",
                            XPathContentFailureString = "AMD.com - Out of Stock"
                        });
                });

            modelBuilder.Entity("Webscan.Scheduler.Models.StatusCheckUser", b =>
                {
                    b.Property<int>("StatusCheckId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StatusCheckId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("StatusCheckUsers");

                    b.HasData(
                        new
                        {
                            StatusCheckId = 1,
                            UserId = 1
                        },
                        new
                        {
                            StatusCheckId = 2,
                            UserId = 1
                        },
                        new
                        {
                            StatusCheckId = 3,
                            UserId = 1
                        },
                        new
                        {
                            StatusCheckId = 4,
                            UserId = 1
                        },
                        new
                        {
                            StatusCheckId = 5,
                            UserId = 1
                        },
                        new
                        {
                            StatusCheckId = 6,
                            UserId = 1
                        },
                        new
                        {
                            StatusCheckId = 7,
                            UserId = 1
                        },
                        new
                        {
                            StatusCheckId = 8,
                            UserId = 1
                        },
                        new
                        {
                            StatusCheckId = 9,
                            UserId = 1
                        },
                        new
                        {
                            StatusCheckId = 10,
                            UserId = 1
                        },
                        new
                        {
                            StatusCheckId = 11,
                            UserId = 1
                        },
                        new
                        {
                            StatusCheckId = 12,
                            UserId = 1
                        },
                        new
                        {
                            StatusCheckId = 13,
                            UserId = 1
                        },
                        new
                        {
                            StatusCheckId = 14,
                            UserId = 1
                        },
                        new
                        {
                            StatusCheckId = 15,
                            UserId = 1
                        },
                        new
                        {
                            StatusCheckId = 16,
                            UserId = 1
                        },
                        new
                        {
                            StatusCheckId = 17,
                            UserId = 1
                        },
                        new
                        {
                            StatusCheckId = 18,
                            UserId = 1
                        },
                        new
                        {
                            StatusCheckId = 1,
                            UserId = 2
                        },
                        new
                        {
                            StatusCheckId = 2,
                            UserId = 2
                        },
                        new
                        {
                            StatusCheckId = 3,
                            UserId = 2
                        },
                        new
                        {
                            StatusCheckId = 4,
                            UserId = 2
                        },
                        new
                        {
                            StatusCheckId = 5,
                            UserId = 2
                        },
                        new
                        {
                            StatusCheckId = 6,
                            UserId = 2
                        },
                        new
                        {
                            StatusCheckId = 7,
                            UserId = 2
                        },
                        new
                        {
                            StatusCheckId = 8,
                            UserId = 2
                        },
                        new
                        {
                            StatusCheckId = 9,
                            UserId = 2
                        },
                        new
                        {
                            StatusCheckId = 10,
                            UserId = 2
                        },
                        new
                        {
                            StatusCheckId = 11,
                            UserId = 2
                        },
                        new
                        {
                            StatusCheckId = 12,
                            UserId = 2
                        },
                        new
                        {
                            StatusCheckId = 13,
                            UserId = 2
                        },
                        new
                        {
                            StatusCheckId = 14,
                            UserId = 2
                        },
                        new
                        {
                            StatusCheckId = 15,
                            UserId = 2
                        },
                        new
                        {
                            StatusCheckId = 16,
                            UserId = 2
                        },
                        new
                        {
                            StatusCheckId = 17,
                            UserId = 2
                        },
                        new
                        {
                            StatusCheckId = 18,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Webscan.Scheduler.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "6513437334@messaging.sprintpcs.com",
                            Username = "Cory"
                        },
                        new
                        {
                            Id = 2,
                            Email = "6129786995@tmomail.net",
                            Username = "Aaron"
                        });
                });

            modelBuilder.Entity("Webscan.Scheduler.Models.StatusCheckUser", b =>
                {
                    b.HasOne("Webscan.Scheduler.Models.StatusCheck", null)
                        .WithMany()
                        .HasForeignKey("StatusCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webscan.Scheduler.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
